// lib/utils.ts
import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatDate(date: Date | string) {
  return new Date(date).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  })
}

export function formatDateTime(date: Date | string) {
  return new Date(date).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  })
}

export function formatDistanceToNow(date: Date | string) {
  const now = new Date()
  const past = new Date(date)
  const diff = now.getTime() - past.getTime()
  const seconds = Math.floor(diff / 1000)
  const minutes = Math.floor(seconds / 60)
  const hours = Math.floor(minutes / 60)
  const days = Math.floor(hours / 24)

  if (days > 0) return `${days}d ago`
  if (hours > 0) return `${hours}h ago`
  if (minutes > 0) return `${minutes}m ago`
  return "just now"
}

export function calculateProgress(current: number, target: number): number {
  if (target === 0) return 0
  return Math.min(Math.round((current / target) * 100), 100)
}

export function getStatusColor(status: string): string {
  const colors: { [key: string]: string } = {
    draft: "bg-gray-100 text-gray-800",
    submitted: "bg-blue-100 text-blue-800",
    approved: "bg-green-100 text-green-800",
    rejected: "bg-red-100 text-red-800",
    in_progress: "bg-yellow-100 text-yellow-800",
    completed: "bg-green-100 text-green-800",
    cancelled: "bg-gray-100 text-gray-800",
    "on track": "bg-green-100 text-green-800",
    "at risk": "bg-red-100 text-red-800",
    "not started": "bg-gray-100 text-gray-800",
    delayed: "bg-red-100 text-red-800",
  }
  return colors[status.toLowerCase()] || "bg-gray-100 text-gray-800"
}

export function getStatusIcon(status: string): string {
  const icons: { [key: string]: string } = {
    draft: "📝",
    submitted: "📤",
    approved: "✅",
    rejected: "❌",
    in_progress: "⚙️",
    completed: "🎉",
    cancelled: "🚫",
    pending: "⏳",
    "on track": "✅",
    "at risk": "⚠️",
    "not started": "⭕",
    delayed: "🔴",
  }
  return icons[status.toLowerCase()] || "📌"
}

export function calculateWeightageSum(goals: any[]): number {
  return goals.reduce((sum, goal) => sum + (goal.weightage || 0), 0)
}

export function calculateHealthScore(metrics: {
  consistency: number
  completion: number
  engagement: number
  trend: number
  discipline: number
}): number {
  return Math.round(
    (metrics.consistency * 0.2 +
      metrics.completion * 0.3 +
      metrics.engagement * 0.2 +
      metrics.trend * 0.15 +
      metrics.discipline * 0.15) /
      100
  )
}

export function generateSMARTGoal(input: string): string {
  // Placeholder: In real implementation, this would call AI API
  return `SMART Goal based on: "${input}". This is a placeholder that will be generated by AI.`
}

export function isOverdue(deadline: Date | string): boolean {
  return new Date(deadline) < new Date()
}

export function getDaysUntilDeadline(deadline: Date | string): number {
  const today = new Date()
  const dead = new Date(deadline)
  const diff = dead.getTime() - today.getTime()
  return Math.ceil(diff / (1000 * 60 * 60 * 24))
}

export function getCurrentQuarter(): string {
  const month = new Date().getMonth() + 1
  if (month <= 3) return "Q1"
  if (month <= 6) return "Q2"
  if (month <= 9) return "Q3"
  return "Q4"
}

export function getCurrentYear(): number {
  return new Date().getFullYear()
}

export function validateWeightage(weightages: number[]): string {
  const sum = weightages.reduce((a, b) => a + b, 0)
  if (sum !== 100) {
    return `Total weightage must be 100%, currently ${sum}%`
  }
  for (const w of weightages) {
    if (w < 10) {
      return "Each goal must have at least 10% weightage"
    }
  }
  return ""
}

export function truncate(str: string, length: number): string {
  return str.length > length ? str.substring(0, length) + "..." : str
}
